require "shenanigans/array"
require "shenanigans/hash"
require "shenanigans/integer"
require "shenanigans/kernel"
require "shenanigans/module"
require "shenanigans/object"
require "shenanigans/string"
