require 'shenanigans/array'
require 'shenanigans/enumerable'
require 'shenanigans/fixnum'
require 'shenanigans/hash'
require 'shenanigans/kernel'
require 'shenanigans/module'
require 'shenanigans/object'
require 'shenanigans/string'
